// SPDX-License-Identifier: AGPL-3.0-or-later
// Regenerate src/panel/logo.ts from assets/nit-32.png. Run by hand after the
// logo changes: `npm run gen:logo`.
import fs from 'node:fs';

const SOURCE = 'assets/nit-32.png';
const OUT = 'src/panel/logo.ts';

const base64 = fs.readFileSync(SOURCE).toString('base64');
fs.writeFileSync(OUT, `// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by scripts/gen-logo.mjs from ${SOURCE} — do not edit by hand.
// Inlined because the panel is a setContent document with no server behind it.
export const NIT_LOGO_DATA_URI = 'data:image/png;base64,${base64}';
`);
console.log(`wrote ${OUT} (${base64.length} chars)`);
